spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/vehicles_db
      database: vehicles_db

logging:
  level:
    org.springframework.data.mongodb: DEBUG
    org.mongodb.driver: DEBUG

